---
- name: Descargar binarios de Prometheus desde GitHub
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.44.0/prometheus-2.44.0.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Crear directorio para Prometheus
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Extraer Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /etc/prometheus
    remote_src: yes

- name: Crear usuario para Prometheus
  user:
    name: prometheus
    shell: /usr/sbin/nologin

- name: Configurar Prometheus
  ansible.builtin.copy:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify:
    - Reiniciar Prometheus

- name: Configurar alertas en Prometheus
  ansible.builtin.copy:
    src: templates/alerts.yml.j2
    dest: /etc/prometheus/alert.rules
  notify:
    - Reiniciar Prometheus

- name: Crear directorio de almacenamiento para Prometheus
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'
  become: yes

- name: Dar permisos a Prometheus para el directorio de almacenamiento
  ansible.builtin.file:
    path: /var/lib/prometheus
    owner: prometheus
    group: prometheus
    mode: '0755'
  become: yes

- name: Crear servicio para Prometheus
  ansible.builtin.copy:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service          
  notify:
    - Reiniciar Prometheus

- name: Descargar Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extraer Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt
    remote_src: true

- name: Eliminar el directorio de Node Exporter si existe
  file:
    path: /opt/node_exporter
    state: absent

- name: Mover Node Exporter
  command: mv /opt/node_exporter-1.6.0.linux-amd64 /opt/node_exporter

- name: Crear servicio para Node Exporter
  template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Iniciar y habilitar Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: true

- name: Iniciar y habilitar Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: true

- name: Agregar clave GPG de Grafana
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: Agregar repositorio de Grafana
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Actualizar la caché de paquetes
  apt:
    update_cache: yes

- name: Instalar Grafana
  apt:
    name: grafana
    state: present

- name: Habilitar e iniciar el servicio de Grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes
