---
- name: Instalar nginx
  apt: 
    name: 
     - nginx
    update-cache: yes

- name: Instalar dependencias de OpenSSL
  apt:
    name:
      - openssl
      - libssl-dev
    state: present

- name: Crear directorio para certificados SSL
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Crear clave privada RSA
  community.crypto.openssl_privatekey:
    path: /etc/nginx/ssl/certificate.key
    size: 4096
    type: RSA

- name: Crear certificado SSL autofirmado
  community.crypto.x509_certificate:
    path: /etc/nginx/ssl/certificate.pem
    privatekey_path: /etc/nginx/ssl/certificate.key
    provider: selfsigned
    selfsigned_digest: sha256

- name: Configurar Nginx para HTTPS
  template:
    src: templates/nginx_https.conf.j2
    dest: "{{ nginx_config_path }}"
  notify:
    - Reiniciar Nginx

- name: Crear enlace para habilitar el sitio HTTPS
  file:
    src: "{{ nginx_config_path }}"
    dest: /etc/nginx/sites-enabled/https_config
    state: link

- name: Habilitar UFW para permitir tráfico HTTPS
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Probar configuración de Nginx
  command: nginx -t