---
- name: Reiniciar Nginx
  service:
    name: nginx
    state: restarted

- name: Recargar systemd
  command: systemctl daemon-reload
  become: yes

- name: Reiniciar Prometheus
  become: true
  systemd:
    name: prometheus
    state: restarted
