Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64" # La vm tendrá un so ubuntu 20.04

  config.vm.network "private_network", type: "dhcp" # configuracion para dar un ip a la vm con dhcp
  config.vm.provider "virtualbox" do |vb| #Configuramos como proveedor a virtualbox
    vb.memory = "1024" # Usará 1gb de ram
    vb.name = "vm_seguridad" # Nombre de la vm
  end
  config.vm.provision "ansible" do |ansible| #Configuramos ansible como provisionador
    ansible.playbook = "site.yml" #leeremos el site.yml un playbook de ansible que crearemos
  end
end
